### ISSUE TITLE
print (bc.HEADER + "Artist of song/album ", end="")

### ISSUE THREAD

**Issue by artpar** [kepoorhampond/irs#1]
Wanted to try this, but isnt working.

```
╭─artpar at artpar-lenovo in ~/Music using
╰─○ irs -a "Tool" -A "10000 days"
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 7, in <module>
    from irs.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/irs/__main__.py", line 51
    print (bc.HEADER + "Artist of song/album ", end="")
                                                   ^
SyntaxError: invalid syntax
╭─artpar at artpar-lenovo in ~/Music using
╰─○ irs -a "Tool" -s "Come as you are"
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 7, in <module>
    from irs.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/irs/__main__.py", line 51
    print (bc.HEADER + "Artist of song/album ", end="")
                                                   ^
SyntaxError: invalid syntax
```

```
╭─artpar at artpar-lenovo in ~/Music using
╰─○ python --version 
Python 2.7.12
╭─artpar at artpar-lenovo in ~/Music using
╰─○ uname -a
Linux artpar-lenovo 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
╭─artpar at artpar-lenovo in ~/Music using
╰─○ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by artpar** [comment]
Hmm, the readme earlier said >=2.7.9 so I was hoping it would work. Will try with python 3 some other time.

**Comment by kepoorhampond** [comment]
I don't think it said that, but I DID just update it to specify that you need >=3.x to run it. Sorry for the vagueness.
