### ISSUE TITLE
unicode choking on '

### ISSUE THREAD

**Issue by encryptednonrandom** [kepoorhampond/irs#14]
$ irs -u "xxxxxxxxxxxx" -p "Proximity"

Traceback (most recent call last):
  File "/usr/bin/irs", line 11, in <module>
    load_entry_point('irs==6.2.2', 'console_scripts', 'irs')()
  File "/usr/lib/python2.7/site-packages/irs-6.2.2-py2.7.egg/irs/cli.py", line 57, in main
    ripper.spotify_list("playlist", args.playlist, args.username)
  File "/usr/lib/python2.7/site-packages/irs-6.2.2-py2.7.egg/irs/ripper.py", line 234, in spotify_list
    locations = self.list(tracks)
  File "/usr/lib/python2.7/site-packages/irs-6.2.2-py2.7.egg/irs/ripper.py", line 247, in list
    loc = self.song(track["name"], track["artist"], track)
  File "/usr/lib/python2.7/site-packages/irs-6.2.2-py2.7.egg/irs/ripper.py", line 300, in song
    video_url, video_title = self.find_yt_url(song, artist)
  File "/usr/lib/python2.7/site-packages/irs-6.2.2-py2.7.egg/irs/ripper.py", line 112, in find_yt_url
    query_string = urlencode({"search_query" : (search_terms)})
  File "/usr/lib64/python2.7/urllib.py", line 1326, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 6: ordinal not in range(128)

irs seems to be having a problem with the single apostrophe in the track "It Ain't Me (with Selena Gomez) - Kygo, Selena Gomez"

Need to find a way for irs to not halt on error as well as log to info/stdout that it wasn't able to parse or process track...skip to next track instead of dump to traceback. 

Also update application version (6.22 > 6.23) on every commit. I want to make sure I'm working with the correct version.

**Comment by encryptednonrandom** [comment]
maybe set default encoding to utf-8?

**Comment by kepoorhampond** [comment]
Fixed with #30
