### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by encryptednonrandom** [kepoorhampond/irs#15]
$ irs -u "xxxxxxxxxxxxxx" -p "Rap Nation"
Playlist: "Rap Nation" by "xxxxxxxxxxxxx"
Traceback (most recent call last):
  File "/usr/bin/irs", line 11, in <module>
    load_entry_point('irs==6.2.2', 'console_scripts', 'irs')()
  File "/usr/lib/python2.7/site-packages/irs-6.2.2-py2.7.egg/irs/cli.py", line 57, in main
    ripper.spotify_list("playlist", args.playlist, args.username)
  File "/usr/lib/python2.7/site-packages/irs-6.2.2-py2.7.egg/irs/ripper.py", line 214, in spotify_list
    album = self.spotify.album(track["album"]["uri"])
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 302, in album
    trid = self._get_id('album', album_id)
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 846, in _get_id
    fields = id.split(':')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by encryptednonrandom** [comment]
https://open.spotify.com/user/allrapnations/playlist/6ZTpgxK6BT92mmsqwETj9l

**Comment by kepoorhampond** [comment]
I can't seem to reproduce this error. Is everything the same in the playlist?

**Comment by kepoorhampond** [comment]
I'm going to close this, if you still have this issue, just reopen it.
