### ISSUE TITLE
KeyError: 'name'

### ISSUE THREAD

**Issue by encryptednonrandom** [kepoorhampond/irs#16]
artists name: Myon x Fatum feat. Marcus Bently
song name: Rain

python3 /usr/local/bin/irs -a "Myon x Fatum feat. Marcus Bently" -s "Rain"

Finding Youtube Link ...
Finding Youtube Link ...
Downloading "Rain" by "Myon x Fatum feat. Marcus Bently" ...
Converting to mp3 ...
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 9, in <module>
    load_entry_point('irs==6.2.2', 'console_scripts', 'irs')()
  File "/usr/local/lib/python3.5/dist-packages/irs-6.2.2-py3.5.egg/irs/cli.py", line 53, in main
    ripper.song(args.song, args.artist)
  File "/usr/local/lib/python3.5/dist-packages/irs-6.2.2-py3.5.egg/irs/ripper.py", line 335, in song
    m.add_tag(    "title",          data["name"])
KeyError: 'name'

**Comment by encryptednonrandom** [comment]
Additional error: 

python3 /usr/local/bin/irs -a "Ruben De Ronde & Rodg" -s "Whoop"
Finding Youtube Link ...
Finding Youtube Link ...
Downloading "Whoop" by "Ruben De Ronde & Rodg" ...
Converting to mp3 ...
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 9, in <module>
    load_entry_point('irs==6.2.2', 'console_scripts', 'irs')()
  File "/usr/local/lib/python3.5/dist-packages/irs-6.2.2-py3.5.egg/irs/cli.py", line 53, in main
    ripper.song(args.song, args.artist)
  File "/usr/local/lib/python3.5/dist-packages/irs-6.2.2-py3.5.egg/irs/ripper.py", line 335, in song
    m.add_tag(    "title",          data["name"])
KeyError: 'name'

**Comment by kepoorhampond** [comment]
Fixed with commit 46ff493. It was a problem with `spotipy` not finding any artist info. Sorry for the long wait, I was on vacation without wifi.
