### ISSUE TITLE
No token provided

### ISSUE THREAD

**Issue by indrajeet007** [kepoorhampond/irs#29]
I am encountering an issue since start of this june. I guess spotify needs to refresh tokens or some other stuff for every request made. So far i have found this as an reference to the issue.

Since May 29th 2017, EVERY request needs to be authorized. :(
They announced it in their web...
https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/

I really dont have any experience as how to solve this issue. Any one can help me through ?

Below is the error i receive in the terminal :- 

Traceback (most recent call last):
  File "/usr/local/bin/irs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/irs/cli.py", line 75, in main
    console(ripper)
  File "/usr/local/lib/python2.7/site-packages/irs/utils.py", line 314, in console
    ripper.song(song_name, artist_name)
  File "/usr/local/lib/python2.7/site-packages/irs/ripper.py", line 348, in song
    data = self.parse_song_data(song, artist)
  File "/usr/local/lib/python2.7/site-packages/irs/ripper.py", line 309, in parse_song_data
    album, track = find_album_and_track(song, artist)
  File "/usr/local/lib/python2.7/site-packages/irs/metadata.py", line 60, in find_album_and_track
    tracks = spotipy.Spotify().search(q=song, type="track"
  File "/usr/local/lib/python2.7/site-packages/spotipy/client.py", line 339, in search
    return self._get('search', q=q, limit=limit, offset=offset, type=type, market=market)
  File "/usr/local/lib/python2.7/site-packages/spotipy/client.py", line 146, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "/usr/local/lib/python2.7/site-packages/spotipy/client.py", line 124, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/search?q=s&type=track&limit=10&offset=0:
 No token provided

**Comment by kepoorhampond** [comment]
Fixed with PR #28, you will need to set up some tokens, so look to the README for some instructions.
