### ISSUE TITLE
irs/config_preset

### ISSUE THREAD

**Issue by indrajeet007** [kepoorhampond/irs#33]
Thanks for looking at the authorisation bug. After updating to the newer irs version (6.6.1), there seems to be an error coming up during setup.

Here's the error from the terminal:

irs --setup

"ffmpeg" is already downloaded!
"ffprobe" is already downloaded!
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 11, in <module>
    load_entry_point('irs==6.6.1', 'console_scripts', 'irs')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/irs/__init__.py", line 13, in <module>
    setup()
  File "/usr/local/lib/python2.7/site-packages/irs/setup_binaries.py", line 12, in setup
    copyfile("irs/config_preset", config_file)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'irs/config_preset'

Is there supposed to be a file named config_present in the irs folder which holds the tokens or maybe i am missing something on my installation ?

Thanks for your help.

**Comment by kepoorhampond** [comment]
Fixed with PR #34
