### ISSUE TITLE
Exception in spotipy

### ISSUE THREAD

**Issue by pakoito** [kepoorhampond/irs#4]
System:

MBP 2015
OSX El Capitan
Python 3.5.1 :: Anaconda 2.5.0 (x86_64)

Trace:

```
Traceback (most recent call last):
  File "/Users/my/stuff/anaconda3/bin/irs", line 11, in <module>
    sys.exit(main())
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/irs/__main__.py", line 106, in main
    manager.rip_spotify_list("album")
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/irs/manager.py", line 157, in rip_spotify_list
    results = spotify.search(q=search, type=type)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/spotipy/client.py", line 339, in search
    return self._get('search', q=q, limit=limit, offset=offset, type=type, market=market)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/spotipy/client.py", line 146, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/spotipy/client.py", line 108, in _internal_call
    r = self._session.request(method, url, headers=headers, proxies=self.proxies, **args)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/Users/my/stuff/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
```

**Comment by kepoorhampond** [comment]
I'll be looking for a way to duplicate and fix the bug!

**Comment by kepoorhampond** [comment]
Could you try to follow the directions [here](https://github.com/conda/conda/issues/3996)?

**Comment by pakoito** [comment]
It gives the same error, but now downloading pyopenssl.py Everything in Anaconda fails now, so it's not a problem with IRS.
