### ISSUE TITLE
Exception on macOS Sierra

### ISSUE THREAD

**Issue by chris-etheridge** [kepoorhampond/irs#5]
```
irs -u "someuser"
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 7, in <module>
    from irs.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/irs/__main__.py", line 47, in <module>
    from .manager import Manager
  File "/usr/local/lib/python2.7/site-packages/irs/manager.py", line 78
    print (bc.YELLOW + "\nFinding youtube link ...", end="\r")
                                                        ^
SyntaxError: invalid syntax
```

```
$ python --version
Python 2.7.12
```

**Comment by kepoorhampond** [comment]
The README says that you need Python 3.x to run it. I won't close the issue until I change that in `setup.cfg`. My bad.

**Comment by chris-etheridge** [comment]
Ah, that is my bad for not reading the readme properly!

Can close.
