### ISSUE TITLE
Bug when searching for one song

### ISSUE THREAD

**Issue by Kezxo** [kepoorhampond/irs#9]
Just typed ``irs``, then ``1`` and ``test``
```
What type of media would you like to download?
        1) Song
        2) Album
        3) Playlist
:: 1
Song you would like to download : test
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/irs/__main__.py", line 112, in main
    manager.console()
  File "/usr/local/lib/python3.5/dist-packages/irs/manager.py", line 47, in console
    self.rip_mp3()
  File "/usr/local/lib/python3.5/dist-packages/irs/manager.py", line 234, in rip_mp3
    audio_code = self.find_mp3(song=song, artist=artist)
  File "/usr/local/lib/python3.5/dist-packages/irs/manager.py", line 65, in find_mp3
    print (color(song, ["BOLD", "UNDERLINE"]) + ' by ' + color(artist, ["BOLD", "UNDERLINE"]))
  File "/usr/local/lib/python3.5/dist-packages/irs/utils.py", line 58, in color
    return (bc.ENDC + eval(color_string) + text + bc.ENDC)
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by kepoorhampond** [comment]
When I get home, I'll try and fix it. Thanks for reporting it!

**Comment by kepoorhampond** [comment]
Fixed it a while ago, forgot to close this issue, sorry.
